import { useAuth, useClerk } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data } = api.posts.getAll.useQuery();
  const { signOut, openSignIn } = useClerk();
  const { isSignedIn } = useAuth();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1>Index.tsx</h1>
        <div>
          {!isSignedIn ? (
            <button onClick={() => openSignIn()}>Sign In</button>
          ) : (
            // eslint-disable-next-line @typescript-eslint/no-misused-promises
            <button onClick={() => signOut()}>Sign Out</button>
          )}
        </div>
        <div>
          {data?.map((post) => (
            <div key={post.id}>{post.content}</div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
