import { UserButton, useUser } from "@clerk/nextjs";
import { formatDistanceToNow } from "date-fns";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { LoadingSpinner } from "~/components/loading";
import { api, type RouterOutputs } from "~/utils/api";

type PostWithUser = RouterOutputs["posts"]["getAll"][number];
const PostView = ({ post, author }: PostWithUser) => {
  return (
    <div key={post.id} className="flex items-center gap-4">
      {author.profileImageUrl && (
        <Image
          width={60}
          height={60}
          className="rounded-full"
          src={author?.profileImageUrl}
          alt="profile image"
        />
      )}
      <div className="flex flex-col gap-2">
        <div className={"flex gap-1"}>
          <span className="font-light">@{author.username}</span>
          <span>·</span>
          <span className="font-thin">
            {formatDistanceToNow(new Date(post.createdAt))}
          </span>
        </div>
        <h3 className="font-bold">{post.content}</h3>
      </div>
    </div>
  );
};

export const Feed = () => {
  const { data, isLoading } = api.posts.getAll.useQuery();
  if (isLoading)
    return (
      <div className="flex h-full w-full justify-center">
        <LoadingSpinner />
      </div>
    );
  return (
    <div>
      {data?.map((fullPostWithAuthor) => (
        <PostView key={fullPostWithAuthor.post.id} {...fullPostWithAuthor} />
      ))}
    </div>
  );
};

const Home: NextPage = () => {
  const { user, isLoaded: userLoaded } = useUser();
  api.posts.getAll.useQuery();

  if (!userLoaded) return <div></div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full flex-col items-center p-6 text-slate-300 md:p-0">
        <div className="container max-w-3xl ">
          <div className="flex justify-between pb-3">
            <h1 className="text-3xl font-bold">Chirp</h1>
            {/* {!isSignedIn ? (
              <button onClick={() => openSignIn()}>Sign In</button>
            ) : (
              <UserButton />
            )} */}
            <UserButton />
          </div>
          <div className="mb-4 flex gap-2 ">
            {user?.profileImageUrl && (
              <Image
                width={60}
                height={60}
                className="rounded-full"
                src={user?.profileImageUrl}
                alt="profile image"
              />
            )}
            <input
              className=" mr-2 w-full flex-grow rounded-md border border-blue-800 bg-transparent p-2 outline-blue-400"
              placeholder="Chirp something..."
            />
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
